declare const styles: {
  readonly "active": string;
  readonly "ant-checkbox-group": string;
  readonly "ant-collapse-arrow": string;
  readonly "ant-collapse-content-box": string;
  readonly "ant-collapse-header": string;
  readonly "ant-collapse-item": string;
  readonly "ant-form-item-control-input-content": string;
  readonly "ant-slider-handle": string;
  readonly "ant-slider-rail": string;
  readonly "ant-slider-tooltip": string;
  readonly "ant-slider-track": string;
  readonly "ant-tooltip-arrow-content": string;
  readonly "ant-tooltip-content": string;
  readonly "ant-tooltip-inner": string;
  readonly "closed": string;
  readonly "field-wrapper": string;
  readonly "filter": string;
  readonly "filter-content": string;
  readonly "filter-header": string;
  readonly "forward-arrow": string;
  readonly "hide": string;
  readonly "icon": string;
  readonly "is-open": string;
  readonly "is-open-level-1": string;
  readonly "is-open-level-2": string;
  readonly "label": string;
  readonly "menu": string;
  readonly "minus": string;
  readonly "range-bar-item": string;
  readonly "range-bar-marks": string;
  readonly "sub-menu": string;
  readonly "sub-menu-item": string;
  readonly "tree": string;
  readonly "withIcon": string;
};
export = styles;

